let suggestions = [
    "Abnormal Psychology",
    "Addiction",
    "ADHD,Adult",
    "ADHD,Childhood",
    "Alcohol Use",
    "Anorexia",
    "Anxiety Disorder",
    "APA Format",
    "Behavioral Psychology",
    "Binge Drinking",
    "Biological Psychology",
    "Biopsychology ",
    "Bipolar Disorder ",
    "Border Personality Disorder",
    "Brain Health",
    "Bulimia",
    "Caffeine Addiction",
    "Cannabis Use",
    "Child Development",
    "Classical Conditioning",
    "Clinical Psychology",
    " Cognitive Behavioral Therapy",
    "Cognitive Development",
    "Cognitive Psychology",
    "Color Psychology",
    " Counselling Psychology",
    "Cross-Cultural Psychology",
    "Depression",
    "Depression,Childhood",
    " Development Psychology",
    "Dreaming",
    "Drug Use",
    "DSM-5",
    "Eating Disorders",
    "Educational Psychology",
    "Emotional Abuse",
    "Emotions",
    "Experimental Psychology",
    "Extroversion",
    "Forensic Psychology",
    "Generalized Anxiety Disorder",
    "Goal Setting",
    "Grief & Loss",
    "Happiness",
    "Health Psychology",
    "Healthy Aging",
    "Hierarchy of Needs",
    "Holistic Health",
    " Household Stress",
    "Inspiration",
    "Intelligence",
    "Introversion",
    "IQ Scores",
    "Job Stress",
    "Learning Styles",
    "LGBTQ",
    "Loneliness",
    "Mania and Hypomania",
    "Marital Issues",
    "Meditation",
    "Memory",
    "Mental Exercises",
    "Mental Health Technology",
    " Mindfulness",
    "Mood Disorders",  
    "Motivation",
    "Nature vs. Nurture",
    "Nicotine Use",
    "Nonverbal Communicaiton",
    "Obsessive-Compulsive Disorder",
    "Online Therapy",
    "Operant Conditioning",
    "Oploid Use",
    "Panic Disorder",
    "Parenting Styles",
    "Passive Aggression",
    "Personal Growth",
    "Personality Disorders",
    "Personality Types",
    "Phobias",
    "Positive Psychology",
    "Psychologist Biographies",
    "Psychology 101",
    "Psychology Careers",
    "Psychology Theories",
    "Psychosexual Development",
    "Psychosocial Development",
    "Psychosocial Psychology",
    "Psychotherapy",
    "PTSD",
    "Quit Smoking",
    "Race and Identity",
    "Recovery",
    "Relationship Stress",
    "Relationships",
    "Schizophrenia",
    "School Psychology",
    "Self-Imrovement",
    "Sex Addiction",
    "Sexuality",
    "Shopping Addiction",
    "Situational Stress",
    "Sleep",
    "Social Anxiety Disorder",
    "Social Learning Theory",
    "Social Psychology",
    "Spirituality",
    "Sports Psychology",
    "Stress Management",
    "Student Resources",
    "Study Guides",
    "Technology Addiction",
    "Therapy Types",
    "Violence and Abuse",
    "Workplace Bullying",


];